#!/usr/bin/env bash
set -euo pipefail

TARGET_FILE="${ACP_SECRET_ENV_FILE:-.secrets/agent-control-plane.env}"
OVERWRITE="${SECRET_ROTATION_OVERWRITE:-false}"
TTL_DAYS="${SECRET_ROTATION_TTL_DAYS:-90}"
AUDIT_FILE="${SECRET_ROTATION_AUDIT_FILE:-.secrets/rotation-audit.log}"

if [[ -e "$TARGET_FILE" && "$OVERWRITE" != "true" ]]; then
  echo "secret_rotation=skipped"
  echo "reason=target_exists"
  echo "target=${TARGET_FILE}"
  echo "set SECRET_ROTATION_OVERWRITE=true to rotate existing values"
  exit 0
fi

mkdir -p "$(dirname "$TARGET_FILE")"
umask 077

random_secret() {
  openssl rand -base64 48 | tr -d '\n'
}

timestamp_now() {
  node -e "console.log(new Date().toISOString())"
}

timestamp_expires_at() {
  node -e "const days = Number(process.argv[1]); if (!Number.isFinite(days) || days <= 0) process.exit(2); console.log(new Date(Date.now() + days * 86400000).toISOString())" "$TTL_DAYS"
}

json_escape() {
  node -e "process.stdout.write(JSON.stringify(process.argv[1]).slice(1, -1))" "$1"
}

append_audit_log() {
  local target="$1"
  local rotated_at="$2"
  local expires_at="$3"
  local variables="$4"
  local audit_file="$AUDIT_FILE"

  if [[ -z "$audit_file" ]]; then
    return 0
  fi

  mkdir -p "$(dirname "$audit_file")"
  umask 077
  local actor="${USER:-unknown}"
  local host
  host="$(hostname 2>/dev/null || printf 'unknown')"
  local line
  line=$(
    printf '{"event":"secret_rotation","target":"%s","rotated_at":"%s","expires_at":"%s","variables":"%s","actor":"%s","host":"%s"}' \
      "$(json_escape "$target")" \
      "$(json_escape "$rotated_at")" \
      "$(json_escape "$expires_at")" \
      "$(json_escape "$variables")" \
      "$(json_escape "$actor")" \
      "$(json_escape "$host")"
  )
  printf '%s\n' "$line" >>"$audit_file"
  chmod 600 "$audit_file"
}

rotated_at="$(timestamp_now)"
expires_at="$(timestamp_expires_at)"
rotated_variables="ACP_OPERATOR_API_TOKEN,ACP_OPERATOR_LOGIN_PASSWORD,ACP_OPERATOR_SESSION_SECRET,PLANE_WEBHOOK_SECRET"
tmp_file="${TARGET_FILE}.tmp"
cat >"$tmp_file" <<EOF
# Generated by scripts/rotate-secrets.sh.
# Keep this file out of git. Required mode: 600 or 400.
ACP_SECRET_ROTATED_AT="${rotated_at}"
ACP_SECRET_EXPIRES_AT="${expires_at}"
ACP_OPERATOR_API_TOKEN="$(random_secret)"
ACP_OPERATOR_LOGIN_PASSWORD="$(random_secret)"
ACP_OPERATOR_SESSION_SECRET="$(random_secret)"
PLANE_WEBHOOK_SECRET="$(random_secret)"
EOF

chmod 600 "$tmp_file"
mv "$tmp_file" "$TARGET_FILE"
append_audit_log "$TARGET_FILE" "$rotated_at" "$expires_at" "$rotated_variables"

cat <<EOF
secret_rotation=completed
target=${TARGET_FILE}
mode=$(stat -f '%Lp' "$TARGET_FILE" 2>/dev/null || stat -c '%a' "$TARGET_FILE" 2>/dev/null || printf 'unknown')
rotated_at=${rotated_at}
expires_at=${expires_at}
rotated=${rotated_variables}
audit_file=${AUDIT_FILE}
EOF
